fix: Unified `tsconfig.json` in all subpackages to eliminate build discrepancies (#487)
## Description
This PR fixes the issue that each package uses a unique `tsconfig.json`
which may lead to different transpilation results.


## Related Issue Or Context
- Discovered by @LyonSsS that `BaseTransfer` constructor was causing
issue

Log:

```
2024-08-20 17:24:45        API/INIT: tangle-testnet/1100: Not decorating unknown runtime apis: 0x7ee4fdd3f4b9d4d0/1, JobsApi/1, 0xa33d43f58731ad84/2
/home/liviu/Sygma/SDK_V3/sygma-sdk/packages/substrate/src/fungible.ts:37
    super(transfer, config);
         ^


TypeError: Class constructor BaseTransfer cannot be invoked without 'new'
    at SubstrateFungibleAssetTransfer (/home/liviu/Sygma/SDK_V3/sygma-sdk/package
```

---------

Co-authored-by: Anton Lykhoyda <lykhoyda@gmail.com>